name: CI Pipeline for Devops2026

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:  
  build-and-test:  
    name: Build & Test  
    runs-on: ubuntu-latest  
 
    # This starts a Postgres database *for this job*  
    services:  
      db:  
        image: postgres:14-alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: myuser  
          POSTGRES_PASSWORD: mypass  
          POSTGRES_DB: mydb
        ports:  
          - 5432:5432
           # This health check ensures the DB is ready before tests run  
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5  
 
    steps:  
        # Step 1: Get our project code onto the runner  
        - name: Checkout code  
          uses: actions/checkout@v3  
 
        # Step 2: Install Node.js v18  
        - name: Setup Node.js  
          uses: actions/setup-node@v3  
          with:  
            node-version: '18'  
            cache: 'npm' # Caches npm packages for faster builds  
 
        # Step 3: Install our app's dependencies  
        - name: Install dependencies  
          run: npm install  
  
        # Step 4: Run the tests. We must provide the DB env vars!  
        - name: Run tests  
          run: npm test  
          env:
            DB_HOST: localhost  
            DB_PORT: 5432  
            DB_USER: postgres  
            DB_PASS: mypass  
            DB_NAME: mydb

  deploy:
    name: Deploy to Server
    runs_on: ubuntu_latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/Devops2026
          git pull origin main
          docker-compose pull
          sudo docker-compose up -d